version: "2"
services:  
    nginx:
        restart: always
        image: nginx:1.12-alpine
        ports:
            - 80:8000
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/app/backend/blockserver/django_static 
    mysql:
        restart: always
        image: mysql/mysql-server:5.6
        ports:
            - "127.0.0.1:3306:3306"
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        command: [
            '--character-set-server=utf8',
            '--collation-server=utf8_unicode_ci'
    ]
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "quant"
            MYSQL_USER: "quant"
            MYSQL_PASSWORD: "quant001@"
    
    redis:
        image: redis:3.0-alpine
        restart: unless-stopped
        ports:
             - "127.0.0.1:6378:6379"
        #build:
        #    context: .
        #    dockerfile: ./docker/redis/
        volumes:
            - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
            - ./docker/redis/data/:/data/
        command: 
            redis-server /usr/local/etc/redis/redis.conf
    rabbitmq:
        image: rabbitmq:3.7-alpine
        restart: unless-stopped
    asgiserver:
        extends:
            file: docker-common.yml
            service: backend
        entrypoint: /app/docker/backend/asgi-entrypoint.sh
        links:
            - mysql
            - redis
            - rabbitmq
        expose:
            - 8000
    worker:
        extends:
            file: docker-common.yml
            service: backend
        entrypoint: /app/docker/backend/worker-entrypoint.sh
        links:
            - mysql
            - redis
            - rabbitmq
volumes:
    static_volume: {}
    


